//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vajehdan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vajehdan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاشینکف
        ///کلاشینکوف
        ///آئروبیک
        ///آیروبیک
        ///آئروبیکی
        ///آیروبیکی
        ///آئرودینامیک
        ///آیرودینامیک
        ///آئروسل
        ///آئروفون
        ///آئرولیت
        ///آئینمند
        ///آئین‌مند
        ///آب آتش‌رنگ
        ///آب آتش‌فام
        ///آب آتشگون
        ///آب آتش‌مزاج
        ///آب آتشین
        ///آب آلبالو
        ///آب آلو
        ///آب آلوده
        ///آب آهک
        ///آب اکسیژنه
        ///آب اماله
        ///آب انار
        ///آب انارین
        ///آب انجیر
        ///آب اندک
        ///آب انگور
        ///آب ایستاده
        ///آب باتری
        ///آب باطری
        ///آب باریک
        ///آب برم
        ///آب بقا
        ///آب بینی
        ///آب پاکی
        ///آب پرتقال
        ///آب پشت
        ///آب تبلور
        ///آب تربت
        ///آب توبه
        ///آب جاری
        ///آب جوش
        ///آب چشم
        ///آب چشمه
        ///آب حرام
        ///آب حمام
        ///آب حیات
        ///آب خالص
        ///آب خضر
        ///آب خنک
        ///آب روان [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Emlaei {
            get {
                return ResourceManager.GetString("Emlaei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرهنگستان
        ///فهرست مصوبات فرهنگستان
        ///
        ///side-chain
        ///زنجیرهٔ جانبی
        ///شاخه
        ///[شیمی] 
        ///*
        ///10-minutes meals diet
        ///رژیم لاغری غذای چنددقیقه‌ای
        ///رژیم لاغری بیست‌وهشت روزه‌ای که مرحله‌بندی ندارد و برای افرادی طراحی شده است که می‌خواهند وقت کمی صرف پختن غذا کنند
        ///[تغذیه] 
        ///*
        ///21-centimeter line, H I line, neutral hydrogen line
        ///خط بیست‌ویک سانتی‌متر
        ///خط طیفی گسیل‌شده از اتم هیدروژن خنثی یا جذب‌شده در آن با بسامد ۱۴۲۰ مگاهرتز
        ///متـ. خط هیدروژن hydrogen line
        ///[نجوم رصدی و آشکارسازها] 
        ///*
        ///3-D quantitative structure activit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Farhangestan {
            get {
                return ResourceManager.GetString("Farhangestan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گنجور
        ///فرهنگ اشعار فارسی
        ///
        ///حافظ | رباعیات | رباعی شمارهٔ ۱
        ///جز نقش تو در نظر نیامد ما را
        ///جز کوی تو رهگذر نیامد ما را
        ///خواب ارچه خوش آمد همه را در عهدت
        ///حقا که به چشم در نیامد ما را
        ///*
        ///حافظ | رباعیات | رباعی شمارهٔ ۲
        ///بر گیر شراب طرب‌انگیز و بیا
        ///پنهان ز رقیب سفله بستیز و بیا
        ///مشنو سخن خصم که بنشین و مرو
        ///بشنو ز من این نکته که برخیز و بیا
        ///*
        ///حافظ | رباعیات | رباعی شمارهٔ ۳
        ///گفتم که لبت، گفت لبم آب حیات
        ///گفتم دهنت، گفت زهی حب نبات
        ///گفتم سخن تو، گفت حافظ گفتا
        ///شادی همه لطیفه گویان صلوات
        ///*
        ///حافظ | رباعیات  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ganjvar {
            get {
                return ResourceManager.GetString("Ganjvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مترادف
        ///فرهنگ مترادف و متضاد فارسی
        ///
        ///آب
        ///ماء
        ///مایع
        ///شیره، عرق، عصاره، عصیر
        ///حل، محلول
        ///ذوب
        ///خوی
        ///بزاق، آب‌دهان
        ///منی
        ///بحر، دریا، یم
        ///زهاب
        ///آبرو، حیثیت، شرف، عزت
        ///تری، تازگی، طراوت
        ///*
        ///آباء
        ///اجداد، اسلاف، پدران، پیشینیان، نیاکان (متضاد: اخلاف) 
        ///*
        ///آباجی
        ///آبجی، اخت، باجی، خواهر، دده، شاباجی، همشیره (متضاد: داداش) 
        ///*
        ///آباد
        ///برپا، دایر، معمور (متضاد: خراب، متروک، ویران) 
        ///پررونق (متضاد: بی‌رونق) 
        ///پیشرفته، توسعه‌یافته، مترقی (متضاد: عقب‌مانده) 
        ///تندرست، سالم
        ///بسامان، منظم
        ///غنی، مرفه
        ///*
        ///آبادان
        ///آباد، برپا، پر [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Motaradef {
            get {
                return ResourceManager.GetString("Motaradef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سره
        ///فرهنگ واژگان سره
        ///
        ///آء
        ///درخت کرنا
        ///*
        ///آب بقا
        ///آب نامیری، آب زندگی، آب جاویدی
        ///*
        ///آب تبلور
        ///گن‌آب، آب‌بلوری
        ///*
        ///آب حسرت
        ///آب رسانه
        ///*
        ///آب حوضی
        ///آب‌کش، آب کش
        ///*
        ///آب حیات
        ///آب زندگی
        ///*
        ///آب حیات
        ///زیست‌آب، زیست آب، جان‌فزا، جان فزا، آب‌زندگی
        ///*
        ///آب خسق
        ///زرتک
        ///*
        ///آب صفا
        ///آب یک‌رنگی
        ///*
        ///آب صفتی
        ///آب‌سرشتی، آبسرشتی، آبخویی
        ///*
        ///آب طرب
        ///می انگوری
        ///*
        ///آب قصیل
        ///خوید چون چید، آب خوید
        ///*
        ///آب قنات
        ///پرشک، پرشک، آب کناد
        ///*
        ///آب قند
        ///آبلوچ، آب غند، آب پانیذ
        ///*
        ///آب معدنی
        ///آب‌کان، آب کانی
        ///*
        ///آب مقطر
        ///چکیده آب، چکیدآب، چکه‌آب [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sereh {
            get {
                return ResourceManager.GetString("Sereh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طیفی
        ///فرهنگ طیفی
        ///
        ///وجود
        ///بودن، کون، هستی، بقا، بود
        ///ذات مطلق، وجود مطلق، ذات خداوندی
        ///ذات
        ///معاش، جان، نفس، زندگی
        ///وجود درزمان، بقا، ابدیت، واقعیت
        ///وجود ازپیش، تقدم
        ///وجود درمکان، حضور
        ///دارایی
        ///به‌وجود آمدن، پیدایش، شدن، تکوین، تکامل، تبدیل
        ///خلق، ایجاد، تولید
        ///بالقوه بودن، امکان، نهفتگی
        ///هستی‌شناسی، انتولوژی، بودشناسی، ماوراءالطبیعه، مابعدالطبیعه، واقع‌گرایی، ایده‌آلیسم، اگزیستانسیالیسم، فلسفه، ماده‌گرایی، ماتریالیسم، مادیت
        ///*
        ///واقعیت
        ///حقیقت داشتن، موجودیت، کیان، هستی
        ///وجود واقعی، مادیت
        ///آن بودن، خاص بودن، و [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Teyfi {
            get {
                return ResourceManager.GetString("Teyfi", resourceCulture);
            }
        }
    }
}
